### ISSUE TITLE
Missing error for undefined variable in DAE

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#2028]
```python
x = SX.sym('x'); z = SX.sym('z'); p = SX.sym('p')
dae = {'x':x, 'z':z, 'ode':z+p, 'alg':z*cos(z)-x} # p forgotten here
F = integrator('F', 'idas', dae)
r = F(x0=0, z0=0, p=0.1)
print(r['xf'])
```

Would make sense if an error were thrown.

**Comment by jaeandersson** [comment]
Need to add an assertion in the OracleFunction class

**Comment by jgillis** [comment]
https://github.com/casadi/casadi/blob/develop/casadi/core/x_function.hpp#L978

This assumption is a bit problematic in light of this bug..

**Comment by jaeandersson** [comment]
> This assumption is a bit problematic in light of this bug..

I'm curious if that hack is still needed. With the support for generalized outputs instructions (#1382)  it might be possible to remove them where they are created.

**Comment by jgillis** [comment]
Solved in 390a06597

**Comment by jaeandersson** [comment]
It's actually not solved yet... the solution is for Nlpsol only..

**Comment by jaeandersson** [comment]
Oh, nevermind
